dist: trusty
sudo: false

addons:
  sonarcloud:
    organization: "s4paneum-organization"
token: $SONAR_TOKEN3



script:
- make clean
# Wraps the compilation with the Build Wrapper to generate configuration (used
# later by the SonarQube Scanner) into the "bw-output" folder
  build-wrapper-win-x86-64.exe --out-dir bw-output make clean all
# Execute some tests
- make test
# And finally run the SonarQube analysis - read the "sonar-project.properties"
# file to see the specific configuration
- sonar-scanner
