sudo: false
language: c

addons:
  sonarcloud:
    organization: "s4paneum-organization"
token: $SONAR_TOKEN2


script:
  sonar-scanner.bat
  -D"sonar.projectKey=s4paneum_wrk"
  -D"sonar.organization=s4paneum-github"
  -D"sonar.sources=."
  -D"sonar.cfamily.build-wrapper-output=bw-output"
  -D"sonar.host.url=https://sonarcloud.io"
  -D"sonar.login=4d274ca64e9f9c62567989cb460c751b8c0ad464"
