dist: trusty
sudo: false

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "c0e7491f4e49b055723b6111b321b3c958997636"
script:
-build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner

cache:
  directories:
  - '$HOME/.sonar/cache'
